version: "3.9"

name: "quiz"

services:
  web:
    build: .
    container_name: web
    command: gunicorn core.wsgi:application --workers 4 --bind 0.0.0.0:8890
#    command: python manage.py runserver 0.0.0.0:8890
    volumes:
      - static_volume:/opt/src/static
      - media_volume:/opt/src/media
#    ports:  не нужны будем проходить по портам nginx
#      - "12345:8890"
    env_file:
      - .env_prod
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8890 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  db:
#    image: postgres:12.0-alpine
    build: ./postgres
    container_name: db
    volumes:
      - db_data_volume:/var/lib/postgresql/data/
      #  открывали для того чтоб DBeaver ом подключиться c локального к-ра
#    ports:
#      - "5439:5432"
    env_file:
      - .env_prod
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "quiz", "-U", "aladin"]
      interval: 30s
      timeout: 2s
      retries: 5
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/opt/src/static
      - media_volume:/opt/src/media
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/src/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always


volumes:
  db_data_volume:
    name: quiz_data
  static_volume:
    name: quiz_static
  media_volume:
    name: quiz_media