version: "3.9"

name: "quiz"

services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8890
    ports:
      - "12345:8890"
    env_file:
      - .env_prod
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8890 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  db:
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - db_data_volume:/var/lib/postgresql/data/
    ports:
      - "5439:5432"
    env_file:
      - .env_prod
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 30s
      timeout: 2s
      retries: 5
    restart: always

volumes:
  db_data_volume:
    name: quiz_data